[variables]
PYTORCH_INSTALL = "cpu"

[phases.setup]
nixPkgs = ["python39", "ffmpeg-headless", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install --no-cache-dir --use-deprecated=legacy-resolver -r requirements.txt"
]

[start]
cmd = "gunicorn app:app -b 0.0.0.0:$PORT -w 4 --timeout 120"
