[phases.setup]
nixPkgs = ["python39", "ffmpeg-headless", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

[variables]
PYTHONUNBUFFERED = "1"
