[phases.setup]
nixPkgs = [
    "ffmpeg",
    "libSM",  # Note the capitalization - this is the correct Nixpkgs name
    "libXext"  # Also capitalized
]

[start]
cmd = "gunicorn app:app -b 0.0.0.0:$PORT -w 4 --timeout 120"